pipeline:
    tox:
        image: ${IMAGE}
        environment:
            - CFLAGS=-O0
            - DB_CACHE=/cache
            - TOX_TESTENV_PASSENV=CFLAGS DB_CACHE
            - POSTGRESQL_URI=postgresql://postgres@postgresql:5432/
        commands:
            - pip install tox
            - tox -e "${TOXENV}-${DATABASE}"

services:
    postgresql:
        image: postgres
        when:
            matrix:
                DATABASE: postgresql

matrix:
    include:
        - IMAGE: kalenis/kalenis-lims-test:3.7
          TOXENV: py37
          DATABASE: postgresql
