# This file is part of lims_planification module for Tryton.
# The COPYRIGHT file at the top level of this repository contains
# the full copyright notices and license terms.

from trytond.pool import Pool
from .configuration import *
from .lims import *
from report import *
from wizard import *


def register():
    Pool.register(
        LimsConfiguration,
        LimsConfigurationSequence,
        LimsLabWorkYear,
        LimsConfigurationProductCategory,
        LimsPlanification,
        LimsPlanificationTechnician,
        LimsPlanificationTechnicianDetail,
        LimsPlanificationDetail,
        LimsPlanificationServiceDetail,
        LimsNotebookLine,
        LimsNotebookLineFraction,
        LimsEntryDetailAnalysis,
        LimsFraction,
        LimsPlanificationServiceDetailLaboratoryProfessional,
        LimsPlanificationAnalysis,
        LimsPlanificationFraction,
        LimsFractionReagent,
        LimsFractionType,
        LimsLaboratoryProfessional,
        LimsLabProfessionalMethod,
        LimsLabProfessionalMethodRequalification,
        LimsLabProfessionalMethodRequalificationSupervisor,
        LimsLabProfessionalMethodRequalificationControl,
        LimsAnalysis,
        LimsService,
        LimsBlindSample,
        LimsRelateTechniciansStart,
        LimsRelateTechniciansResult,
        LimsRelateTechniciansDetail1,
        LimsRelateTechniciansDetail2,
        LimsRelateTechniciansDetail3,
        LimsUnlinkTechniciansStart,
        LimsUnlinkTechniciansDetail1,
        LimsAddFractionControlStart,
        LimsAddFractionRMBMZStart,
        LimsAddFractionBREStart,
        LimsAddFractionMRTStart,
        LimsRemoveControlStart,
        LimsAddAnalysisStart,
        LimsSearchFractionsNext,
        LimsSearchFractionsDetail,
        LimsSearchPlannedFractionsStart,
        LimsSearchPlannedFractionsNext,
        LimsSearchPlannedFractionsDetail,
        LimsCreateFractionControlStart,
        LimsReleaseFractionStart,
        LimsReleaseFractionEmpty,
        LimsReleaseFractionResult,
        LimsQualificationSituations,
        LimsQualificationSituation,
        LimsQualificationAction,
        LimsQualificationSituation2,
        LimsQualificationSituation3,
        LimsQualificationSituation4,
        LimsReplaceTechnicianStart,
        PrintBlindSampleReportStart,
        PrintPendingServicesUnplannedReportStart,
        module='lims_planification', type_='model')
    Pool.register(
        LimsRelateTechnicians,
        LimsUnlinkTechnicians,
        LimsAddFractionControl,
        LimsAddFractionRMBMZ,
        LimsAddFractionBRE,
        LimsAddFractionMRT,
        LimsRemoveControl,
        LimsAddAnalysis,
        LimsSearchFractions,
        LimsSearchPlannedFractions,
        LimsCreateFractionControl,
        LimsReleaseFraction,
        LimsTechniciansQualification,
        LimsReplaceTechnician,
        LimsManageServices,
        LimsLoadServices,
        PrintBlindSampleReport,
        PrintPendingServicesUnplannedReport,
        module='lims_planification', type_='wizard')
    Pool.register(
        LimsPlanificationSequenceReport,
        LimsPlanificationWorksheetAnalysisReport,
        LimsPlanificationWorksheetMethodReport,
        LimsPlanificationWorksheetReport,
        LimsPendingServicesUnplannedReport,
        LimsPendingServicesUnplannedSpreadsheet,
        LimsBlindSampleReport,
        LimsPlanificationSequenceAnalysisReport,
        module='lims_planification', type_='report')
